### ISSUE TITLE
export_content raises AttributeError: get with Plone 2.8.7 

### ISSUE THREAD

**Issue by rpijlman** [collective/collective.jsonify#47]
Same issue as #48

Commit 192fed7db6f8d8fcf5612c830229f93ab3b2314e in collective.jsonify 1.5 causes an exception in export_content with Zope 2.8.7-final, python 2.3.5, linux3:

Traceback (most recent call last):
  File "/home/software/zope/2.8/lib/python/ZPublisher/Publish.py", line 114, in publish
    request, bind=1)
  File "/home/software/zope/2.8/lib/python/ZPublisher/mapply.py", line 88, in mapply
    if debug is not None: return debug(object,args,context)
  File "/home/software/zope/2.8/lib/python/ZPublisher/Publish.py", line 40, in call_object
    result=apply(object,args) # Type s<cr> to step into published object.
  File "/home/software/zope/2.8/lib/python/Products/ExternalMethod/ExternalMethod.py", line 225, in __call__
    try: return f(*args, **kw)
  File "/home/zope/productie/Extensions/json_methods.py", line 16, in export_content
    extra_skip_classname=[],  # optional list of classnames to skip
  File "/home/software/python/2.3.5/lib/python2.3/site-packages/collective.jsonify-1.5-py2.3.egg/collective/jsonify/export.py", line 266, in export_content
    write(walk(self, skip_callback=skip_callback))
  File "/home/software/python/2.3.5/lib/python2.3/site-packages/collective.jsonify-1.5-py2.3.egg/collective/jsonify/export.py", line 337, in write
    for item in items:
  File "/home/software/python/2.3.5/lib/python2.3/site-packages/collective.jsonify-1.5-py2.3.egg/collective/jsonify/export.py", line 299, in walk
    item = folder.get(item_id)
AttributeError: get

**Comment by rpijlman** [comment]
Duplicate of #48

**Comment by ale-rt** [comment]
Sorry I missed you already opened an issue for this!
